CREATE PROC FI_SP_IncBeneficiario
    @IDCLIENTE     BIGINT,
	@CPF           VARCHAR (11),
	@NOME          VARCHAR (50)
AS
BEGIN
	INSERT INTO 
		BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
	VALUES 
		(@NOME, @CPF, @IDCLIENTE)
	SELECT SCOPE_IDENTITY()
END